24 Update set up files
pharmaverse/admiralophtha pull request #25
Opened 2022-09-30 11:23 UTC by millerg23

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [ ] Update to all relevant roxygen headers and examples.
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page.
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue so that it closes after successful merging.
- [ ] Address all merge conflicts and resolve appropriately.
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

2022-09-30 11:26 UTC, millerg23 commented
When I ran `pkgdown::build_site()` it doesn't generate the README.md file using README.Rmd. I also getting a NOTE when running `devtools::document()` about a time stamp not being found??
Any help appreciated!

2022-09-30 11:39 UTC, bundfussr commented
I think `README.md` is generated by the "Render README" workflow. If you want to create it locally, you could try `rmarkdown::render("README.Rmd", output_format = "md_document")`. I have not tried it but it's what the workflow does.

2022-10-03 11:21 UTC, millerg23 commented
@bundfussr @cicdguy would you say we can accept the LINKs failing for now? Think everything else is working OK

2022-10-04 09:13 UTC, millerg23 commented
@bundfussr  you happy for me to merge this? Do you see anything I missed? Thanks!

2022-10-04 16:49 UTC, bundfussr requested changes
- `.Rbuildignore` should be updated. There are references to admiralext. And the entries for the vignettes do not make sense.
- `Authors@R:`, `Description:`, and `URL:` in `DESCRIPTION` should be updated.
- I would remove all the entries in `R/globals.R` because it will be hard to remove the unnecessary ones later.
- I would remove `R/my_first_fnc.R`, `man/hello_admiral.Rd`, and `tests/testthat/test-my_first_fcn.R`.

2022-10-04 16:49 UTC, bundfussr commented on .Rhistory
>  renv::restore()
This file should be removed.

2022-10-04 16:49 UTC, bundfussr commented on _pkgdown.yml
> +    issue: https://github.com/pharmaverse/admiralonco/issues/
It should be `admiralophta` instead of `admiralonco` and `main` instead of `test` for `source:`.

2022-10-05 12:02 UTC, millerg23 commented
@bundfussr thanks for the great feedback, I think I have made all the updates. Also added the information to generate README in a feature branch (copied from admiraltemplate).

2022-10-05 12:08 UTC, bundfussr approved these changes

2022-10-05 12:10 UTC, merged